/**
 * StellarTicket contract client.
 *
 * A small typed wrapper around the deployed Soroban contract using
 * `@stellar/stellar-sdk` directly. This avoids relying on the autogenerated
 * scaffold bindings so the project type-checks even before `stellar scaffold`
 * has produced a client. If the scaffold-generated bindings are present in
 * `src/contracts/stellar_ticket.ts`, you can use them interchangeably.
 */
import {
	Account,
	Address,
	BASE_FEE,
	Contract,
	Networks,
	TransactionBuilder,
	nativeToScVal,
	rpc,
	scValToNative,
	type xdr,
} from "@stellar/stellar-sdk"
import { networkPassphrase, rpcUrl } from "../contracts/util"
import { wallet } from "../util/wallet"

export interface TicketingEvent {
	id: string
	organiser: string
	name: string
	description: string
	venue: string
	event_date: bigint
	ticket_price: bigint
	ticket_asset: string
	total_supply: number
	tickets_sold: number
	created_at: bigint
	is_cancelled: boolean
}

export type TicketStatus = "Valid" | "Used" | "Cancelled" | "Refunded"

export interface Ticket {
	id: string
	event_id: string
	owner: string
	status: TicketStatus
	purchased_at: bigint
	used_at: bigint | null
	seat_or_tier: string | null
	tx_hash: string
}

const STATUSES: TicketStatus[] = ["Valid", "Used", "Cancelled", "Refunded"]

function getContractId(): string {
	const id = process.env.NEXT_PUBLIC_TICKETING_CONTRACT_ID
	if (!id) {
		throw new Error(
			"NEXT_PUBLIC_TICKETING_CONTRACT_ID is not set. Deploy the stellar-ticket contract and add it to your .env (see .env.example).",
		)
	}
	return id
}

function getServer(): rpc.Server {
	return new rpc.Server(rpcUrl, { allowHttp: rpcUrl.startsWith("http://") })
}

function networkPassphraseFor(): string {
	// `networkPassphrase` is exported from contracts/util as the WalletNetwork
	// enum value (a string in the SDK's `Networks` set).
	return networkPassphrase as unknown as string
}

/** Decode an arbitrary ScVal returned by simulation/invoke to a JS value. */
function decode(val: xdr.ScVal): unknown {
	return scValToNative(val)
}

/** Read-only call: simulate and decode the result. */
async function simulateRead(
	method: string,
	args: xdr.ScVal[],
): Promise<unknown> {
	const server = getServer()
	const contract = new Contract(getContractId())
	// Simulation does not require a funded source account; an in-memory
	// Account with a placeholder sequence is sufficient.
	const sourceAccount = new Account(
		"GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI",
		"0",
	)

	const tx = new TransactionBuilder(sourceAccount, {
		fee: BASE_FEE,
		networkPassphrase: networkPassphraseFor(),
	})
		.addOperation(contract.call(method, ...args))
		.setTimeout(60)
		.build()

	const sim = await server.simulateTransaction(tx)
	if (rpc.Api.isSimulationError(sim)) {
		throw new Error(`Simulation failed: ${sim.error}`)
	}
	const retval = sim.result?.retval
	if (!retval) return undefined
	return decode(retval)
}

/** Write call: build, simulate, sign with wallet, submit, await success. */
async function invokeWrite(
	method: string,
	source: string,
	args: xdr.ScVal[],
): Promise<unknown> {
	const server = getServer()
	const contract = new Contract(getContractId())
	const sourceAccount = await server.getAccount(source)

	const built = new TransactionBuilder(sourceAccount, {
		fee: BASE_FEE,
		networkPassphrase: networkPassphraseFor(),
	})
		.addOperation(contract.call(method, ...args))
		.setTimeout(60)
		.build()

	const prepared = await server.prepareTransaction(built)
	const xdrStr = prepared.toXDR()

	const { signedTxXdr } = await wallet.signTransaction(xdrStr, {
		networkPassphrase: networkPassphraseFor(),
		address: source,
	})

	const signed = TransactionBuilder.fromXDR(signedTxXdr, networkPassphraseFor())

	const sendResp = await server.sendTransaction(signed)
	if (sendResp.status === "ERROR") {
		throw new Error(
			`sendTransaction failed: ${JSON.stringify(sendResp.errorResult ?? sendResp)}`,
		)
	}

	// Poll for completion
	let status = await server.getTransaction(sendResp.hash)
	const start = Date.now()
	while (status.status === "NOT_FOUND" && Date.now() - start < 30_000) {
		await new Promise((r) => setTimeout(r, 1000))
		status = await server.getTransaction(sendResp.hash)
	}

	if (status.status !== "SUCCESS") {
		throw new Error(`Transaction failed: ${status.status}`)
	}
	if ("returnValue" in status && status.returnValue) {
		return decode(status.returnValue)
	}
	return undefined
}

// ---------- Helpers to build ScVals ----------

const sStr = (v: string) => nativeToScVal(v, { type: "string" })
const sU64 = (v: bigint | number) =>
	nativeToScVal(typeof v === "number" ? BigInt(v) : v, { type: "u64" })
const sU32 = (v: number) => nativeToScVal(v, { type: "u32" })
const sI128 = (v: bigint) => nativeToScVal(v, { type: "i128" })
const sAddr = (v: string) => new Address(v).toScVal()

// ---------- Normalisation helpers ----------

function normaliseEvent(raw: unknown): TicketingEvent {
	const e = raw as Record<string, unknown>
	return {
		id: String(e.id),
		organiser: String(e.organiser),
		name: String(e.name),
		description: String(e.description),
		venue: String(e.venue),
		event_date: BigInt(e.event_date as string | number | bigint),
		ticket_price: BigInt(e.ticket_price as string | number | bigint),
		ticket_asset: String(e.ticket_asset),
		total_supply: Number(e.total_supply),
		tickets_sold: Number(e.tickets_sold),
		created_at: BigInt(e.created_at as string | number | bigint),
		is_cancelled: Boolean(e.is_cancelled),
	}
}

function normaliseTicket(raw: unknown): Ticket {
	const t = raw as Record<string, unknown>
	const statusRaw = t.status as { tag?: string } | string | number
	let status: TicketStatus = "Valid"
	if (typeof statusRaw === "string") {
		status = (statusRaw as TicketStatus) ?? "Valid"
	} else if (typeof statusRaw === "number") {
		status = STATUSES[statusRaw] ?? "Valid"
	} else if (statusRaw && typeof statusRaw === "object" && statusRaw.tag) {
		status = statusRaw.tag as TicketStatus
	}
	const usedAt = t.used_at as bigint | string | number | null | undefined
	return {
		id: String(t.id),
		event_id: String(t.event_id),
		owner: String(t.owner),
		status,
		purchased_at: BigInt(t.purchased_at as string | number | bigint),
		used_at:
			usedAt === null || usedAt === undefined
				? null
				: BigInt(usedAt as string | number | bigint),
		seat_or_tier:
			t.seat_or_tier === null || t.seat_or_tier === undefined
				? null
				: String(t.seat_or_tier),
		tx_hash: String(t.tx_hash ?? ""),
	}
}

// ---------- Public API ----------

export async function createEvent(params: {
	id: string
	organiser: string
	name: string
	description: string
	venue: string
	eventDate: bigint
	ticketPrice: bigint
	ticketAsset: string
	totalSupply: number
}): Promise<TicketingEvent> {
	const raw = await invokeWrite("create_event", params.organiser, [
		sStr(params.id),
		sAddr(params.organiser),
		sStr(params.name),
		sStr(params.description),
		sStr(params.venue),
		sU64(params.eventDate),
		sI128(params.ticketPrice),
		sStr(params.ticketAsset),
		sU32(params.totalSupply),
	])
	return normaliseEvent(raw)
}

export async function purchaseTicket(params: {
	ticketId: string
	eventId: string
	buyer: string
	paidAmount: bigint
}): Promise<Ticket> {
	const raw = await invokeWrite("purchase_ticket", params.buyer, [
		sStr(params.ticketId),
		sStr(params.eventId),
		sAddr(params.buyer),
		sI128(params.paidAmount),
	])
	return normaliseTicket(raw)
}

export async function markTicketUsed(args: {
	ticketId: string
	verifier: string
}): Promise<Ticket> {
	const raw = await invokeWrite("use_ticket", args.verifier, [
		sStr(args.ticketId),
		sAddr(args.verifier),
	])
	return normaliseTicket(raw)
}

export async function cancelTicket(params: {
	ticketId: string
	owner: string
}): Promise<Ticket> {
	const raw = await invokeWrite("cancel_ticket", params.owner, [
		sStr(params.ticketId),
		sAddr(params.owner),
	])
	return normaliseTicket(raw)
}

export async function getEvent(eventId: string): Promise<TicketingEvent> {
	const raw = await simulateRead("get_event", [sStr(eventId)])
	return normaliseEvent(raw)
}

export async function getTicket(ticketId: string): Promise<Ticket> {
	const raw = await simulateRead("get_ticket", [sStr(ticketId)])
	return normaliseTicket(raw)
}

export async function isUsed(ticketId: string): Promise<boolean> {
	const raw = await simulateRead("is_used", [sStr(ticketId)])
	return Boolean(raw)
}

export async function getEventTickets(eventId: string): Promise<string[]> {
	const raw = (await simulateRead("get_event_tickets", [sStr(eventId)])) as
		| string[]
		| undefined
	return raw ?? []
}

export async function getOrganiserEvents(organiser: string): Promise<string[]> {
	const raw = (await simulateRead("get_organiser_events", [
		sAddr(organiser),
	])) as string[] | undefined
	return raw ?? []
}

export async function ticketsRemaining(eventId: string): Promise<number> {
	const raw = await simulateRead("tickets_remaining", [sStr(eventId)])
	return Number(raw)
}

// Ensure unused import lint pass for `Networks` (used implicitly when toggling networks).
export const _knownNetworks = Networks
